# Add feature request to the project board
#
name: project_automation
on:
  issues:
    types:
      - labeled
env:
  gh_project_token: ${{ secrets.GHPROJECT_TOKEN }}
  project_id: 1
  gh_organization: "rderbier"
  status_todo: "ASAP"
jobs:
  add-to-project:
    name: add_feature_request
    if: github.event.label.name == 'kind/feature'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 'Move issue to ${{ env.status_new }}'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        env:
          DEBUG_LOG: "true"
        with:
          gh_token: ${{ env.gh_project_token }}
          organization: ${{ env.gh_organization }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.status_todo }}
