on:
  issues:
    types:
      - opened

jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: Create Doc in Cycle
      run: |
        response = $( curl https://api.product.cycle.app/graphql -X POST -H "Content-Type: application/json" \
  --data '{
     "query": "mutation { login(email: \"${{secrets.CYCLE_USER}}\", password: \"${{secrets.CYCLE_PASSW}}\") { token } }"
     }' )
        echo "response from curl= $response"
       
